services:
    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
         
         MYSQL_ROOT_PASSWORD: ${handon2}
         MYSQL_DATABASE: ${handon2}
         MYSQL_USER: ${handon2}
         MYSQL_PASSWORD: ${handon2}
        ports:
        - "3306:3306"
        volumes:
        - mysql_data:/var/lib/mysql
        networks:
        - handon2
    
    phpmyadmin:
       image: phpmyadmin/phpmyadmin
       restart: unless-stopped
       environment:
        PMA_HOST: mysql
       
        PMA_USER: ${handon2}
        PMA_PASSWORD: ${handon2}
       ports:
        - "8082:80"
       depends_on:
        - mysql
       networks:
        - handon2

volumes:
    mysql_data:

networks:
    handon2: